Famelo:
  Common:
    pagination:
      defaultLimit: 10
      maxPages: 10
      limits:
        - 10
        - 20
        - 30
        - 50
        - 100
TYPO3:
  Flow:
    object:
      excludeClasses:
       'davidbadura.fixtures' : ['.*']
       'DavidBadura.Fixtures' : ['.*']
       'fzaninotto.faker':      ['.*']